### ISSUE TITLE
What do you think to create a one-for-all page? 

### ISSUE THREAD

**Issue by frederikhors** [besoeasy/tailwind-components#1]
What do you think to create a one-for-all page? 

I would like to see all components quickly.

Thanks for your work.

**Comment by besoeasy** [comment]
Relative Components will mess up !

i was thinking to display components screenshots instead of names, but that's for future

**Comment by frederikhors** [comment]
I think the screenshots are too messy to do.

**Comment by besoeasy** [comment]
well thats a option for now !
